import type { LacFile, LocalizedText, SolutionSpec } from "@/lib/domain/types";
import { TEMPLATES } from "@/lib/templates";

// Deploy-guide README bundled into every LaC ZIP. English, since it rides
// along with the JSON files into customer-facing repos.

const HUB_LABEL: Record<string, string> = {
  // hub_a's two firewalls are role-separated (DMZ ingress / internal
  // egress+east-west), not a redundant pair — do not label them "HA".
  hub_a: "Hub A — two OCI Network Firewalls (DMZ + internal)",
  hub_b: "Hub B — one OCI Network Firewall",
  hub_c: "Hub C — trust/untrust Network Load Balancers for third-party firewalls",
  hub_e: "Hub E — no traffic inspection (cost-free hub)",
};

export function buildLacReadme(spec: SolutionSpec, generated: LacFile[], assumptions: LocalizedText[]): string {
  const t = TEMPLATES[spec.template];
  const names = generated.map((f) => f.path.replace(/^generated\//, ""));
  const pre = names.filter((n) => n.includes("_pre"));
  const finals = names.filter((n) => !n.includes("_pre"));
  const staged = pre.length > 0;

  return `# ${t.name.en} — OCI Landing Zone package

Generated by the presale self-service app from the
[OCI Open LZ Blueprint Factory](https://github.com/oci-landing-zones/oci-landing-zone-operating-entities/tree/master/addons/oci-lz-blueprint-factory)
(config-driven mode of \`gen/generate.sh\`). Review everything before deployment.

- Region: **${spec.region.id}** (naming short code \`${spec.region.shortName}\`)
- Hub model: **${HUB_LABEL[spec.hub.kind] ?? spec.hub.kind}**
- CIS profile: **Level ${spec.cisLevel}**
- Environments: **${spec.environments.join(", ")}**

## Contents

- \`config.json\` — the Blueprint Factory input (source of truth; keep in Git)
- \`generated/\` — orchestrator-ready landing zone configuration:
${names.map((n) => `  - \`${n}\``).join("\n")}

## How to deploy

The generated JSON files are inputs to the
[OCI Landing Zones Orchestrator](https://github.com/oci-landing-zones/terraform-oci-modules-orchestrator)
(validated against v2.1.3), via Terraform CLI or OCI Resource Manager:

- Terraform guide: https://github.com/oci-landing-zones/oci-landing-zone-operating-entities/blob/master/commons/content/terraform.md
- Resource Manager guide: https://github.com/oci-landing-zones/oci-landing-zone-operating-entities/blob/master/commons/content/orm.md

${staged
    ? `This hub model uses a **staged (two-step) deployment**:

1. **Step 1** — apply the \`*_pre\` files together with \`iam.json\` / \`governance.json\`:
${pre.map((n) => `   - \`${n}\``).join("\n")}
2. **Step 2** — after the firewall endpoints exist, replace each \`*_pre\` file
   with its final counterpart and re-apply:
${finals.map((n) => `   - \`${n}\``).join("\n")}

   ${spec.hub.kind === "hub_a" || spec.hub.kind === "hub_b"
      ? `Before applying Step 2, edit \`network.json\` and replace every route-rule
   \`network_entity_id\` still set to the literal placeholder
   \`"OCI NFW PRIVATE IP OCID, e.g. ocid1.privateip..."\` with the private-IP
   OCID of the Network Firewall created in Step 1 (see the One-OE runtime
   guide for where to copy it from).`
      : `Follow the hub-specific Step 2 notes in the One-OE runtime guide
   (backend registration for third-party firewalls).`}
`
    : `Apply all files in a single orchestrator run:
${finals.map((n) => `- \`${n}\``).join("\n")}
`}
Reference runtime docs: https://github.com/oci-landing-zones/oci-landing-zone-operating-entities/blob/master/blueprints/one-oe/runtime/one-stack/readme.md

## Scope

The landing zone deploys **network, IAM, governance, security and
observability** (plus OKE clusters/workers when an OKE platform is part of the
design). Application VMs, databases and AI services shown in the BOM are
**provisioned after the landing zone** inside the project compartments it
creates.

## Assumptions

${assumptions.map((a) => `- ${a.en}`).join("\n")}

## Regenerating

\`\`\`bash
bash gen/generate.sh --config config.json generated
\`\`\`

(from the root of the oci-landing-zone-operating-entities repository)
`;
}
