import type { EnvName } from "./types";

// Deterministic CIDR plan mirroring the repo's canonical layout
// (gen/defaults.libsonnet + blueprint-factory examples):
//   hub                 10.0.0.0/21
//   prod spoke          10.0.64.0/21    prod platform (OKE)     10.0.96.0/20
//   preprod spoke       10.0.128.0/21   preprod platform (OKE)  10.0.160.0/20
//   others continue at 10.0.192.0/21 ... (staging/uat/dev/test)
//
// Platform VCNs are /20 because the oke_simple auto-subnet profile "small"
// asserts exactly a /20 platform VCN (gen/workload-extensions/oke/simple).
// The jsonnet generator asserts non-overlap again; this module is just the
// friendly first line of defence and keeps all templates consistent.

export const HUB_VCN = "10.0.0.0/21";

const ENV_ORDER: EnvName[] = ["prod", "preprod", "staging", "uat", "dev", "test"];

interface EnvBlock {
  spoke: string;
  platform: string;
}

// Each environment owns a /18-sized lane: spoke /21 at lane start, platform
// /20 at lane start + 32 (matches the repo's prod=64, preprod=128 layout).
const LANE_START: Record<EnvName, number> = {
  prod: 64,
  preprod: 128,
  staging: 192,
  uat: 0, // 10.1.x lane (see thirdOctetBase below)
  dev: 64,
  test: 128,
};

const SECOND_OCTET: Record<EnvName, number> = {
  prod: 0,
  preprod: 0,
  staging: 0,
  uat: 1,
  dev: 1,
  test: 1,
};

export function envBlocks(env: EnvName): EnvBlock {
  const start = LANE_START[env];
  const second = SECOND_OCTET[env];
  return {
    spoke: `10.${second}.${start}.0/21`,
    platform: `10.${second}.${start + 32}.0/20`,
  };
}

export function orderEnvs(envs: EnvName[]): EnvName[] {
  return ENV_ORDER.filter((e) => envs.includes(e));
}

/** OKE services CIDR: Kubernetes-internal range, must not overlap VCNs. */
export const OKE_SERVICES_CIDR = "10.96.0.0/16";

/**
 * Hub subnets are auto-generated by the generator as consecutive /24s from the
 * hub VCN in a fixed per-hub order (gen/config.libsonnet). Index of the "mgmt"
 * subnet per hub kind lets us compute api_endpoint_allowed_cidrs.
 *   hub_e: [lb, mgmt, mon, dns]           -> mgmt = .1
 *   hub_b: [lb, fw, mgmt, mon, dns]       -> mgmt = .2
 *   hub_a: [fw-dmz, lb, fw-int, mgmt,...] -> mgmt = .3
 *   hub_c: [untrust, trust, lb, mgmt,...] -> mgmt = .3
 */
const HUB_MGMT_INDEX: Record<string, number> = {
  hub_e: 1,
  hub_b: 2,
  hub_a: 3,
  hub_c: 3,
};

export function hubMgmtSubnet(hubKind: string): string {
  const idx = HUB_MGMT_INDEX[hubKind] ?? 1;
  return `10.0.${idx}.0/24`;
}

// --- lightweight overlap check (friendlier error before jsonnet runs) ------

function cidrRange(cidr: string): { lo: number; hi: number } | null {
  const m = cidr.match(/^(\d+)\.(\d+)\.(\d+)\.(\d+)\/(\d+)$/);
  if (!m) return null;
  const [, a, b, c, d, p] = m.map(Number);
  if ([a, b, c, d].some((x) => x > 255) || p > 32) return null;
  const ip = ((a << 24) >>> 0) + (b << 16) + (c << 8) + d;
  const size = 2 ** (32 - p);
  const lo = Math.floor(ip / size) * size;
  return { lo, hi: lo + size - 1 };
}

export function findOverlap(cidrs: { name: string; cidr: string }[]): string | null {
  const ranges = cidrs
    .map((c) => ({ ...c, range: cidrRange(c.cidr) }))
    .filter((c): c is { name: string; cidr: string; range: { lo: number; hi: number } } => c.range !== null);
  for (let i = 0; i < ranges.length; i++) {
    for (let j = i + 1; j < ranges.length; j++) {
      const a = ranges[i], b = ranges[j];
      if (a.range.lo <= b.range.hi && b.range.lo <= a.range.hi) {
        return `${a.name} (${a.cidr}) overlaps ${b.name} (${b.cidr})`;
      }
    }
  }
  return null;
}
