import type { BomItem, SolutionSpec, TemplateDefinition, WebAppSizing } from "@/lib/domain/types";
import { hours } from "@/lib/bom/formulas";
import { lzBaselineAssumptions, lzBaselineBom } from "./lz-baseline";
import { baseFactoryConfig } from "./common";
import { perEnv } from "@/lib/bom/env";

// 3-tier web application: hub + spoke per environment (web/app/db subnets
// auto-generated by the LZ), app VMs + DB priced per environment.

function sizing(spec: SolutionSpec): WebAppSizing {
  if (spec.sizing.kind !== "web_app") throw new Error("sizing/template mismatch");
  return spec.sizing;
}

export const webAppTemplate: TemplateDefinition = {
  id: "web_app",
  name: { th: "Web Application (3-tier)", en: "Web Application (3-tier)" },
  description: {
    th: "เว็บแอปมาตรฐาน: Load Balancer → App VMs → Database บน landing zone แบบ hub-spoke",
    en: "Standard web app: Load Balancer → App VMs → Database on a hub-spoke landing zone",
  },
  icon: "🌐",
  defaultHub: "hub_b",
  defaultCis: 1,
  defaults(): SolutionSpec {
    return {
      template: "web_app",
      region: { id: "ap-singapore-1", shortName: "sin" },
      cisLevel: 1,
      hub: { kind: "hub_b", connectivity: "none" },
      environments: ["prod"],
      sizing: {
        kind: "web_app",
        appVmCount: 2,
        ocpusPerVm: 2,
        memGbPerVm: 16,
        bootGbPerVm: 100,
        ha: true,
        db: { engine: "adb_serverless", ecpus: 4, storageGb: 200 },
        lbBandwidthMbps: 100,
        waf: false,
      },
      assumptionNotes: [],
    };
  },
  knobs: [
    { path: "sizing.appVmCount", label: { th: "จำนวน App VM ต่อ environment", en: "App VMs per environment" }, input: { type: "number", min: 1, max: 20, unit: "VM" } },
    { path: "sizing.ocpusPerVm", label: { th: "OCPU ต่อ VM", en: "OCPUs per VM" }, input: { type: "number", min: 1, max: 32, unit: "OCPU" } },
    { path: "sizing.memGbPerVm", label: { th: "Memory ต่อ VM (GB)", en: "Memory per VM (GB)" }, input: { type: "number", min: 4, max: 256, step: 4, unit: "GB" } },
    { path: "sizing.bootGbPerVm", label: { th: "Boot volume ต่อ VM (GB)", en: "Boot volume per VM (GB)" }, input: { type: "number", min: 50, max: 1000, step: 50, unit: "GB" } },
    { path: "sizing.ha", label: { th: "High Availability (กระจาย fault domain)", en: "High availability (fault-domain spread)" }, input: { type: "boolean" } },
    {
      path: "sizing.db.engine",
      label: { th: "ฐานข้อมูล", en: "Database" },
      input: {
        type: "select",
        options: [
          { value: "adb_serverless", label: { th: "Autonomous DB Serverless (แนะนำ)", en: "Autonomous DB Serverless (recommended)" } },
          { value: "base_db_vm", label: { th: "Base Database บน VM (Enterprise)", en: "Base Database on VM (Enterprise)" } },
          { value: "none", label: { th: "ไม่ใช้ DB ของ OCI", en: "No OCI database" } },
        ],
      },
    },
    { path: "sizing.db.ecpus", label: { th: "DB ECPU", en: "DB ECPUs" }, input: { type: "number", min: 2, max: 64, step: 2, unit: "ECPU" }, visibleIf: (s) => sizing(s).db.engine !== "none" },
    { path: "sizing.db.storageGb", label: { th: "DB storage (GB)", en: "DB storage (GB)" }, input: { type: "number", min: 20, max: 10000, step: 20, unit: "GB" }, visibleIf: (s) => sizing(s).db.engine !== "none" },
    { path: "sizing.lbBandwidthMbps", label: { th: "LB bandwidth (Mbps)", en: "LB bandwidth (Mbps)" }, input: { type: "number", min: 10, max: 2000, step: 10, unit: "Mbps" } },
    { path: "sizing.waf", label: { th: "เปิด Web Application Firewall", en: "Enable Web Application Firewall" }, input: { type: "boolean" } },
  ],
  buildFactoryConfig(spec) {
    return baseFactoryConfig(spec, "app1");
  },
  buildBom(spec): BomItem[] {
    const s = sizing(spec);
    const vmCount = Math.max(s.appVmCount, s.ha ? 2 : 1);

    // shared (hub) items
    const shared: BomItem[] = [
      ...lzBaselineBom(spec),
      {
        catalogKey: "lb_bandwidth",
        label: { th: `LB bandwidth ${s.lbBandwidthMbps} Mbps`, en: `LB bandwidth ${s.lbBandwidthMbps} Mbps` },
        category: "network",
        quantity: s.lbBandwidthMbps,
        unit: "Mbps",
        monthlyMetricQty: hours(s.lbBandwidthMbps),
        deployedByLz: true,
      },
    ];
    if (s.waf) {
      shared.push({
        catalogKey: "waf_requests_m",
        label: { th: "WAF — requests (สมมติ 30M req/เดือน)", en: "WAF — requests (assumes 30M req/month)" },
        category: "security",
        quantity: 30,
        unit: "M requests",
        monthlyMetricQty: 30_000_000 / 1_000_000,
        deployedByLz: false,
      });
    }

    // per-environment workload (one line set per env)
    const workload = perEnv(spec, () => {
      const list: BomItem[] = [
        {
          catalogKey: "compute_e5_ocpu",
          label: { th: `App VM ×${vmCount} (E5.Flex ${s.ocpusPerVm} OCPU) — OCPU`, en: `App VMs ×${vmCount} (E5.Flex ${s.ocpusPerVm} OCPU) — OCPU` },
          category: "compute",
          quantity: vmCount * s.ocpusPerVm,
          unit: "OCPU",
          monthlyMetricQty: hours(vmCount * s.ocpusPerVm),
          deployedByLz: false,
        },
        {
          catalogKey: "compute_e5_mem",
          label: { th: "App VM — memory", en: "App VMs — memory" },
          category: "compute",
          quantity: vmCount * s.memGbPerVm,
          unit: "GB",
          monthlyMetricQty: hours(vmCount * s.memGbPerVm),
          deployedByLz: false,
        },
        {
          catalogKey: "block_storage_gb",
          label: { th: "Boot volumes", en: "Boot volumes" },
          category: "storage",
          quantity: vmCount * s.bootGbPerVm,
          unit: "GB",
          monthlyMetricQty: vmCount * s.bootGbPerVm,
          deployedByLz: false,
        },
        {
          catalogKey: "block_vpu",
          label: { th: "Boot volume performance (Balanced)", en: "Boot volume performance (Balanced)" },
          category: "storage",
          quantity: vmCount * s.bootGbPerVm,
          unit: "GB",
          monthlyMetricQty: vmCount * s.bootGbPerVm * 10,
          deployedByLz: false,
        },
      ];
      if (s.db.engine === "adb_serverless") {
        list.push(
          {
            catalogKey: "adb_ecpu",
            label: { th: "Autonomous DB — ECPU", en: "Autonomous DB — ECPU" },
            category: "database",
            quantity: s.db.ecpus,
            unit: "ECPU",
            monthlyMetricQty: hours(s.db.ecpus),
            deployedByLz: false,
          },
          {
            catalogKey: "adb_storage_gb",
            label: { th: "Autonomous DB — storage", en: "Autonomous DB — storage" },
            category: "database",
            quantity: s.db.storageGb,
            unit: "GB",
            monthlyMetricQty: s.db.storageGb,
            deployedByLz: false,
          },
        );
      } else if (s.db.engine === "base_db_vm") {
        list.push(
          {
            catalogKey: "base_db_ecpu",
            label: { th: "Base Database Enterprise — ECPU", en: "Base Database Enterprise — ECPU" },
            category: "database",
            quantity: s.db.ecpus,
            unit: "ECPU",
            monthlyMetricQty: hours(s.db.ecpus),
            deployedByLz: false,
          },
          {
            catalogKey: "base_db_infra_ecpu",
            label: { th: "Base Database — compute infrastructure", en: "Base Database — compute infrastructure" },
            category: "database",
            quantity: s.db.ecpus,
            unit: "ECPU",
            monthlyMetricQty: hours(s.db.ecpus),
            deployedByLz: false,
            notes: { th: "รุ่น ECPU คิดค่า infra แยกจาก license — คิดต่อเนื่องแม้ DB หยุด", en: "ECPU model bills infrastructure separately from license — accrues even when the DB is stopped" },
          },
          {
            catalogKey: "base_db_storage_gb",
            label: { th: "Base Database — storage", en: "Base Database — storage" },
            category: "database",
            quantity: s.db.storageGb,
            unit: "GB",
            monthlyMetricQty: s.db.storageGb,
            deployedByLz: false,
          },
        );
      }
      return list;
    });

    return [...shared, ...workload];
  },
  assumptions(spec) {
    const s = sizing(spec);
    const list = lzBaselineAssumptions(spec);
    list.push({
      th: `App tier ใช้ VM.Standard.E5.Flex ในซับเน็ต app ของ spoke แต่ละ environment (${spec.environments.join(", ")}) — public ingress ผ่าน LB ที่ hub`,
      en: `App tier uses VM.Standard.E5.Flex in each environment's spoke app subnet (${spec.environments.join(", ")}) — public ingress via the hub LB`,
    });
    if (s.ha)
      list.push({
        th: "HA: กระจาย VM ≥2 ตัวต่าง fault domain และตั้ง LB health check",
        en: "HA: ≥2 VMs spread across fault domains with LB health checks",
      });
    return list;
  },
};
